# Generated by Django 5.0.7 on 2024-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_pizza_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priceM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('priceL', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bImage', models.URLField(default='https://example.com/default.jpg')),
            ],
        ),
    ]
